version: 2
jobs:
  build:
    working_directory: ~/voyager_helpers

    docker:
      - image: circleci/ruby:2.4.2-node-browsers
        environment:
          RAILS_ENV: test

    steps:
      - checkout

      - restore_cache:
          keys:
          - voyager_helpers-{{ checksum "Gemfile" }}-2
          - voyager_helpers-

      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --without development production --jobs 4 --retry 3

      - save_cache:
          key: voyager_helpers-{{ checksum "Gemfile" }}-2
          paths:
            - vendor/bundle

      - run:
          name: Rspec
          command: bundle exec rspec spec
          environment:
            RAILS_ENV: test
